VERSION="2.2.1"

ACCOUNTS=["GAY2HYXMC7DY6HKP5JQLLGRB4IV3ZLYVLEAFHCURX62XHFY2GI2EBLUE"]

[DOCUMENTATION]
ORG_NAME="Blue Origin"
ORG_URL="https://www.blueorigin-stellar.com/"
ORG_DESCRIPTION="Blue Origin was founded by Jeff Bezos with the vision of enabling a future where millions of people are living and working in space for the benefit of Earth"
ORG_LOGO="https://www.blueorigin-stellar.com/blue.png"


[[CURRENCIES]]
code="BLUE"
status="live"
display_decimals=4
issuer="GAY2HYXMC7DY6HKP5JQLLGRB4IV3ZLYVLEAFHCURX62XHFY2GI2EBLUE"
anchor_asset_type="crypto"
name="Blue Origin"
desc="Blue Origin was founded by Jeff Bezos with the vision of enabling a future where millions of people are living and working in space for the benefit of Earth"
image="https://www.blueorigin-stellar.com/blue.png"
