VERSION="2.2.1"

ACCOUNTS=["GAL53RRAZEMYPCAZC6YEJFNA46FGQ3YIIW5HOGXU2TGLN4CGQYEINVDA"]

[DOCUMENTATION]
ORG_NAME="NVIDIA"
ORG_URL="https://www.stellar-nvda.com/"
ORG_DESCRIPTION="NVIDIA invents the GPU and drives advances in AI, HPC, gaming, creative design, autonomous vehicles, and robotics."
ORG_LOGO="https://www.stellar-nvda.com/nvda.png"


[[CURRENCIES]]
code="NVDA"
status="live"
display_decimals=4
issuer="GAL53RRAZEMYPCAZC6YEJFNA46FGQ3YIIW5HOGXU2TGLN4CGQYEINVDA"
anchor_asset_type="crypto"
name="NVIDIA"
desc="NVIDIA invents the GPU and drives advances in AI, HPC, gaming, creative design, autonomous vehicles, and robotics."
image="https://www.stellar-nvda.com/nvda.png"
