VERSION="2.2.1"

ACCOUNTS=["GDHFQUE5MP7ZS7CLHALUEWQCXXDAURHPUOCK6GNXA3JLHFWNIG2OORCL"]

[DOCUMENTATION]
ORG_NAME="Oracle"
ORG_URL="https://www.oracle-stellar.org/"
ORG_DESCRIPTION="Oracle Corporation is an American multinational computer technology company headquartered in Austin, Texas, United States. In 2020, Oracle was the third-largest software company in the world by revenue and market capitalization."
ORG_LOGO="https://www.oracle-stellar.org/orcl.png"


[[CURRENCIES]]
code="ORCL"
status="live"
display_decimals=3
issuer="GDHFQUE5MP7ZS7CLHALUEWQCXXDAURHPUOCK6GNXA3JLHFWNIG2OORCL"
anchor_asset_type="crypto"
name="Oracle"
desc="Oracle Corporation is an American multinational computer technology company headquartered in Austin, Texas, United States. In 2020, Oracle was the third-largest software company in the world by revenue and market capitalization."
image="https://www.oracle-stellar.org/orcl.png"
