VERSION="2.2.1"

ACCOUNTS=["GCF5IRGGW3ZXVRY7PIOEZX4MAOZYLZELPZFNXSM6W3Z7ILZ2RRV5JFQD"]

[DOCUMENTATION]
ORG_NAME="WallStreetBets"
ORG_URL="https://www.wsb-stellar.com/"
ORG_DESCRIPTION="WallStreetBets is a subreddit dedicated to conversations about options trading and stocks, often referred to simply as /r/wallstreetbets."
ORG_LOGO="https://www.wsb-stellar.com/wsb.png"


[[CURRENCIES]]
code="WSB"
status="live"
display_decimals=2
issuer="GCF5IRGGW3ZXVRY7PIOEZX4MAOZYLZELPZFNXSM6W3Z7ILZ2RRV5JFQD"
anchor_asset_type="crypto"
name="WallStreetBets"
desc="WallStreetBets is a subreddit dedicated to conversations about options trading and stocks, often referred to simply as /r/wallstreetbets."
image="https://www.wsb-stellar.com/wsb.png"
